Vagrant.configure("2") do |config|
  # Usar Ubuntu 20.04 LTS (puedes cambiar la versión)
  config.vm.box = "ubuntu/focal64"

  # Configuración de red (puedes modificar la IP si lo necesitas)
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configurar recursos de la VM
  config.vm.provider "virtualbox" do |vb|
	  vb.name = "ubuntu_vagrant_VM" #nombre de la maquina como se vera en Virtualbox
    vb.memory = "4096"  # Asigna 4GB de RAM
    vb.cpus = 3         # Asigna 3 núcleos de CPU
	  vb.customize ["modifyvm", :id, "--snapshotfolder", "C:\Users\mikel\VirtualBox VMs"] # cambia la ruta del archivo de la VM
  end

  # Sincronizar una carpeta entre el host (Windows) y la VM.
  config.vm.synced_folder ".", "/home/vagrant/shared"

  # Comandos a ejecutar al iniciar la VM
  config.vm.provision "shell", inline: <<-SHELL
    #actualizar el SO
	echo "Actualizando SO..."
    sudo apt-get update -y
    sudo apt-get upgrade -y

    #crear usuario mikel
	echo "Creando usuario mikel..."
	  sudo useradd -m -s /bin/bash mikel
    echo "mikel:mikel" | sudo chpasswd
    #crear carpeta .ssh para recibir la clave publica
    sudo mkdir -p /home/mikel/.ssh
    sudo chmod 700 /home/mikel/.ssh
	  sudo chown mikel:mikel /home/mikel/.ssh
    #anyadir mikel al grupo sudo
	  sudo usermod -aG sudo mikel

    #instalar miniconda con el user mikel
	echo "Instalando miniconda..."
    sudo -u mikel -i mkdir -p /home/mikel/miniconda3
    sudo -u mikel -i wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /home/mikel/miniconda3/miniconda.sh
    sudo -u mikel -i bash /home/mikel/miniconda3/miniconda.sh -b -u -p /home/mikel/miniconda3
    sudo -u mikel -i rm /home/mikel/miniconda3/miniconda.sh

	#clonar el repo con el user mikel
	echo "Clonando repositorio..."
	sudo -u mikel -i git clone https://github.com/mikel314/devproject
	sudo -u mikel -i git config --global user.email mikel314@gmail.com
	sudo -u mikel -i git config --global user.name mikel314

	#ejecutar scrip shell con los comandos que no deja ejecutar bien desde el vagrant. Ver doc
	echo "Ejecutando script post_ionstalls.sh"
  sudo chmod +x /home/mikel/devproject/infra/post_installs.sh
	sudo -u mikel -i /home/mikel/devproject/infra/post_installs.sh

  SHELL

  # copiar la clave publica en authorized_keys
  config.vm.provision "shell" do |s|
	ssh_pub_key = File.readlines("C:/users/mikel/.ssh/ubuntu_server_key.pub").first.strip
	s.inline = <<-SHELL
	echo #{ssh_pub_key} >> /home/mikel/.ssh/authorized_keys
	echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
	SHELL
  end

end
