Vagrant.configure("2") do |config|
  # Usar Ubuntu 20.04 LTS (puedes cambiar la versión)
  config.vm.box = "ubuntu/focal64"

  # Configuración de red (puedes modificar la IP si lo necesitas)
  config.vm.network "private_network", type: "dhcp"

  # Configurar recursos de la VM
  config.vm.provider "virtualbox" do |vb|
	vb.name = "ubuntu_vagrant_VM"
    	vb.memory = "2048"  # Asigna 2GB de RAM
    	vb.cpus = 2         # Asigna 2 núcleos de CPU
	vb.customize ["modifyvm", :id, "--snapshotfolder", "C:\Users\mikel\VirtualBox VMs"]
  end

  # Sincronizar una carpeta entre el host (Windows) y la VM
  config.vm.synced_folder ".", "/home/vagrant/shared"

  # Comandos a ejecutar al iniciar la VM
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install -y build-essential curl
  SHELL
end
