Vagrant.configure("2") do |config|
  # Usar Ubuntu 20.04 LTS (puedes cambiar la versión)
  config.vm.box = "ubuntu/focal64"

  # Configuración de red (puedes modificar la IP si lo necesitas)
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configurar recursos de la VM
  config.vm.provider "virtualbox" do |vb|
	vb.name = "ubuntu_vagrant_VM"
    vb.memory = "2048"  # Asigna 2GB de RAM
    vb.cpus = 2         # Asigna 2 núcleos de CPU
	vb.customize ["modifyvm", :id, "--snapshotfolder", "C:\Users\mikel\VirtualBox VMs"]
  end

  # Sincronizar una carpeta entre el host (Windows) y la VM
  config.vm.synced_folder ".", "/home/vagrant/shared"

  # Comandos a ejecutar al iniciar la VM
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y openssh-server
    sudo systemctl enable ssh
    sudo systemctl start ssh

    # Crear usuario "mikel" con contraseña "mikel"
    echo "mikel:mikel" | sudo chpasswd

    # Permitir autenticación por contraseña en SSH
    sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sudo systemctl restart ssh
  SHELL
end
